### ISSUE TITLE
Add option to deploy via S3

### ISSUE THREAD

**Issue by albinekb** [LinusU/scandium#41]
For deployments over 50MB.

**Comment by albinekb** [comment]
`--bucket=<arn>`? Or how do you think we implement this best? I can do a PR 👍

**Comment by albinekb** [comment]
These are the options that we need to send to createFunction and updateFunction
```
  S3Bucket: "myBucket", 
  S3Key: "myKey", 
  S3ObjectVersion: "1", 
```

How should we store the filed in S3? Update the same zip and use `S3ObjectVersion` to select the latest one? That would make rollbacks easy?

**Comment by LinusU** [comment]
Hmm, is `S3ObjectVersion` required though? I think that the rollbacks will work since you can rollback to any particular Lambda version anyhow?

I think that you need to specifically create a versioned bucket for the `S3ObjectVersion` approach to work, which is a bit of a downside...

Otherwise, `S3Key` could just be `${name}-${revHash(zipData)}.zip`

`--bucket=<arn>` sounds good 👍

**Comment by LinusU** [comment]
rev-hash: https://github.com/sindresorhus/rev-hash
